name: picguard
description: "Your pictures, your signature."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.15+439

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.1'

dependencies:
  app_settings_plus: ^5.2.0+1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  file_picker: ^9.0.2
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^10.0.0
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.12
  form_builder_validators: ^11.1.2
  gap: ^3.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  keyboard_dismisser: ^3.0.0
  logging: ^1.3.0
  multi_image_picker_view: ^3.0.0
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  sentry_flutter: ^8.13.2
  sentry_logging: ^8.13.2
  shared_preferences: ^2.5.2
  slang_flutter: ^4.5.0
  syncfusion_flutter_sliders: ^28.2.9
  synchronized: ^3.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  import_sorter: ^4.6.0
  lint_staged: ^0.5.1
  msix: ^3.16.8
  slang_build_runner: ^4.5.0
  very_good_analysis: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#     - logo/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
          weight: 400
        - asset: fonts/Merriweather-Bold.ttf
          weight: 700
    - family: MerriweatherSans
      fonts:
        - asset: fonts/MerriweatherSans-Regular.ttf
          weight: 400
        - asset: fonts/MerriweatherSans-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: PlayfairDisplaySC
      fonts:
        - asset: fonts/PlayfairDisplaySC-Regular.ttf
          weight: 400
        - asset: fonts/PlayfairDisplaySC-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: fonts/SourceSans3-Bold.ttf
          weight: 700
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
          weight: 400

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# If you publish your app to the Microsoft Store, 
# the installation package will be signed automatically by the store.
msix_config:
  display_name: PicGuard
  logo_path: logo\logo-512.png
  languages: en-us, zh-cn
  architecture: x64
  capabilities: "internetClient,picturesLibrary"
  install_certificate: false

  # msix_version: 1.0.0.0 # If not set, the value of `version` is used
  # With Your Own Certificate 
  certificate_path: CERTIFICATE_PATH_PLACEHOLDER
  certificate_password: CERTIFICATE_PASSWORD_PLACEHOLDER

  # For Publish To Windows Store
  identity_name: IDENTITY_NAME_PLACEHOLDER
  publisher: PUBLISHER_PLACEHOLDER
  publisher_display_name: PUBLISHER_NAME_PLACEHOLDER

import_sorter:
  ignored_files: # Optional, defaults to []
    - \/lib\/gen\/*
    - \/lib\/i18n\/*

lint_staged:
  'lib/**.dart': fvm dart run import_sorter:main lib\/* test\/* && git add --all
