display_name: PicGuard Pro
icon: logo/pro/logo-512.png
summary: Your pictures, your signature.
description: |
  Introducing **PicGuard Pro** - the ultimate solution for securing and customizing your digital photos. With our app, you can easily add watermarks to your images to protect your creative work and maintain your privacy.

  **PicGuard Pro** offers robust privacy protection features, ensuring your personal and sensitive information remains safeguarded. It's highly customizable, allowing you to personalize watermarks with various fonts, styles, and designs to suit your needs.

  Accessible on web, mobile, and desktop, you can seamlessly integrate and manage your watermarking tasks across all your devices. **PicGuard Pro**, as an open-source tool, it's not only free but also continuously improved by a community of developers dedicated to providing the best user experience.

  Download **PicGuard Pro** today and take control of your photo security and personalization like never before!
vendor: kjxbyz
packager: kjxbyz
packagerEmail: hello@kjxbyz.com
license: GPL-3.0-only
url: https://github.com/picguard/picguard
build_arch: x86_64

metainfo: linux/shared/picguard-pro.metainfo.xml

keywords:
  - PicGuard
  - PicGuard Pro
  - Watermark
  - Assistant
  - Watermark Assistant

generic_name: PicGuard Pro

categories:
  - Utility

startup_notify: true
