display_name: PicGuard

icon: logo/logo-512.png

keywords:
  - PicGuard
  - Watermark
  - Assistant
  - Watermark Assistant

generic_name: PicGuard

#actions:
#  - name: Say Hi
#    label: say-hi
#    arguments:
#      - --say
#      - hi
#  - name: Say Bye
#    label: say-bye
#    arguments:
#      - --say
#      - bye

categories:
  - Utility

metainfo: linux/shared/picguard.metainfo.xml

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []
