name: Release web
run-name: Release web ${{ github.ref_name }}

on:
  # Enable manual run
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  web-free:
    name: Create web (free)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies for Linux
        run: |
          # https://github.com/getsentry/sentry-dart/issues/2504
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl libcurl4-openssl-dev git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.10'

      - name: Configure .env
        run: echo "$ENV_PROD_BASE64" | base64 --decode > .env
        env:
          ENV_PROD_BASE64: ${{ secrets.ENV_PROD_BASE64 }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build flutter
        run: flutter build web --dart-define-from-file=.env --dart-define GIT_COMMIT_SHA="$GIT_COMMIT_SHA" --target lib/main_free.dart
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}

      - name: Copy files to flutter web
        run: cp LICENSE README.md ./build/web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PG_PAGES_TOKEN }}
          publish_dir: ./build/web
          cname: web.picguard.app

      - name: Clean up
        if: ${{ always() }}
        run: rm -f .env

  web-pro:
    name: Create web (pro)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies for Linux
        run: |
          # https://github.com/getsentry/sentry-dart/issues/2504
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl libcurl4-openssl-dev git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.10'

      - name: Configure .env
        run: echo "$ENV_PROD_BASE64" | base64 --decode > .env
        env:
          ENV_PROD_BASE64: ${{ secrets.ENV_PROD_BASE64 }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build flutter
        run: |
          cp -r $GITHUB_WORKSPACE/web/pro/* $GITHUB_WORKSPACE/web/
          flutter build web --dart-define-from-file=.env --dart-define GIT_COMMIT_SHA="$GIT_COMMIT_SHA" --target lib/main_pro.dart
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}

      - name: Copy files to flutter web
        run: cp LICENSE README.md ./build/web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PG_PAGES_TOKEN }}
          external_repository: picguard/pro-web
          publish_branch: main  # default: gh-pages
          publish_dir: ./build/web
          cname: pro.picguard.app

      - name: Clean up
        if: ${{ always() }}
        run: rm -f .env
