name: Test Linux deb (free arm64)

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  deb:
    name: Create linux deb
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies for Linux
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl libcurl4-openssl-dev git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Install ayatana-appindicator3-0.1
        run: |
          # used by tray_manager
          sudo apt-get install -y libayatana-appindicator3-dev

      - name: Setup Flutter
        shell: bash
        run: |
          chmod +x ./scripts/install-flutter-github-actions.sh
          ./scripts/install-flutter-github-actions.sh

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Configure .env
        run: echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Install fastforge
        run: dart pub global activate fastforge

      - name: Update make_config.yaml
        run: rm -f "$(pwd)/linux/packaging/deb/make_config-pro.yaml"

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - name: Build deb
        run: |
          export SENTRY_NATIVE_BACKEND=breakpad
          fastforge package \
            --skip-clean \
            --flutter-build-args "dart-define-from-file=.env,target=lib/main_free.dart" \
            --platform linux \
            --targets deb \
            --artifact-name '{{name}}-{{build_name}}.{{build_number}}-{{platform}}-aarch64.{{ext}}'

      # Package the build.
      - name: Copy build for deb
        run: ls -laR
        working-directory: dist

      - uses: actions/upload-artifact@v4
        with:
          name: linux-deb-arm64-artifact
          path: ./dist/**/*.deb

      - name: Clean up
        if: ${{ always() }}
        run: rm -f .env
